### ISSUE TITLE
Achromatomaly isn't real?

### ISSUE THREAD

**Issue by Andrewp2** [annieversary/bevy_color_blindness#1]
For some reason, the youtube algorithm decided that I was one of the 4,000 people to watch this [this video](https://www.youtube.com/watch?v=kYZ00B5O_VQ) which makes the argument that Achromatomaly isn't a real condition, but was something accidentally made up by a programmer in the 2000s who was extrapolating from Achromatopsia in a reasonable but non-valid way.

I don't know if we should leave it in for completeness, or provide some sort of warning that it's not a real color blindness, or maybe leave it in fully because it has some value for some other reason. I'm definitely not an expert on these matters either way so I just wanted to pass this news to you.

**Comment by annieversary** [comment]
Wow. That explains why I could barely find any reliable info on it!

I lean towards leaving it in, it's pretty widespread and people might ask for it if it's missing. I'll link to the video to prevent further spread of misinformation though. Thanks for letting me know!
